name: lingufranca_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  webview_flutter: ^4.8.0
  video_player: ^2.11.1
  flutter_cached_pdfview: ^0.4.3
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
    - assets/icon/

